### PR TITLE
Fix error response

### LINKED ISSUE #1: When use @InjectInitFields(), emit type error

### PR DESCRIPTION
**Pull request by kwonmory**
fix #1

### CODE REVIEW

File: src/decorators/fields.ts [hunk 1]
```diff
@@ -38,7 +38,11 @@ export const InjectInitFields = (
       for (const [name, value] of target) {
         if (~exceptFields.indexOf(name)) continue;
 
-        this[name] = _.cloneDeep(value);
+        try {
+          this[name] = _.cloneDeep(value);
+        } catch (error) {
+          console.log('Fix this problems', error);
```
Comment (kwonmory) [inline src/decorators/fields.ts:44]: will change this
